WebAzBank/Models/BaseModel.cs
namespace BankApp.WebAzBank.Models
{
    public class BaseModel
    {
        public int Id { get; set; }
        public int No { get; set; }
    }
}

WebAzBank/Models/Branch/BranchModel.cs
using BankApp.WebAzBank.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BankApp.WebAzBank.Model
{
    public class BranchModel : BaseModel
    {
        public string BranchName { get; set; }

        public string Adress { get; set; }

        public string Phone { get; set; }

        public string BeginWorkTime { get; set; }

        public string EndWorkTime { get; set; }

        public int CountWorkers { get; set; }

        public bool IsDeleted { get; set; }
    }
}

WebAzBank/Models/Branch/BranchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BankApp.WebAzBank.Model
{
    public class BranchViewModel
    {
        public List<BranchModel> Branches { get; set; }
        public string Message { get; set; }
    }
}

WebAzBank/Models/Client/ClientModel.cs
using BankApp.WebAzBank.Models;

namespace WebAzBank.Models.Client
{
	public class ClientModel : BaseModel
	{
        public string Name { get; set; }
        public string Surname { get; set; }
        public string FatherName { get; set; }
        public string FIN { get; set; }
        public string Seriya { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public int AccountNumber { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Citizenship { get; set; }
        public string Studies { get; set; }
        public string Email { get; set; }
        public DateTime PassportEndTime { get; set; }
        public DateTime BirthDate { get; set; } = DateTime.Now;
        public DateTime AccountingTime { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public DateTime PassportSubmissionTime { get; set; } = DateTime.Now;
        public bool IsDeleted { get; set; }
    }
}

WebAzBank/Models/Client/ClientViewModel.cs
using System.Collections.Generic;

namespace WebAzBank.Models.Client
{
	public class ClientViewModel
	{
		public List<ClientModel> Clients { get; set; }
	}
}

WebAzBank/Models/MenuModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WasherWeb.Areas.Owners.Models
{
    public static class MenuModelExtensions
    {
        public static bool HaveInMenu(this CommonMenuModel menuModel, string action, out int menuOrder, out string menuName)
        {
            menuOrder = -1;
            menuName = string.Empty;

            string lowerAction = action.ToLower();

            if(menuModel is ParentMenuModel parentMenu)
            {
                var childModel = parentMenu.ChildModels.FirstOrDefault(x => x.Action.ToLower() == lowerAction);

                if (childModel == null)
                    return false;

                menuName = childModel.Name;
                menuOrder = childModel.Order;
            }
            else if(menuModel is MenuModel mainMenuModel)
            {
                if(mainMenuModel.Action.ToLower() == lowerAction)
                {
                    menuOrder = mainMenuModel.Order;
                    menuName = mainMenuModel.Name;
                }
            }

            return menuOrder != -1;
        }
    }

    public class CommonMenuModel
    {
        public CommonMenuModel(string name)
        {
            Name = name;
        }

        public string Name { get; set; }
    }

    public class ParentMenuModel : CommonMenuModel
    {
        public ParentMenuModel(string name, List<MenuModel> childModels) : base(name)
        {
            ChildModels = childModels;
        }

        public List<MenuModel> ChildModels { get; set; } = new List<MenuModel>();
    }

    public class MenuModel : CommonMenuModel
    {
        public MenuModel(int order, string name, string action, string controller) : base(name)
        {
            Order = order;
            Action = action;
            Controller = controller;
        }


        public int Order { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    }
}

WebAzBank/Controllers/BranchController.cs
using BankApp.Core.DataAccess.Abstract;
using BankApp.WebAzBank.Mappers;
using BankApp.WebAzBank.Model;
using Microsoft.AspNetCore.Mvc;
using WebAzBank.Models.Client;

namespace BankApp.WebAzBank.Controllers
{
    public class BranchController : Controller
    {
        private readonly IUnitOfWork db;

        public BranchController(IUnitOfWork db)
        {
            this.db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var branches = db.BranchesRepository.Get();

            BranchMapper branchMapper = new BranchMapper();
            List<BranchModel> branchModels = new List<BranchModel>();

            for (int i = 0; i < branches.Count; i++)
            {
                var branch = branches[i];
                var branchModel = branchMapper.Map(branch);

                branchModel.No = i + 1;
                branchModels.Add(branchModel);
            }

            BranchViewModel viewModel = new BranchViewModel()
            {
                Branches = branchModels
            };

            if (TempData["Message"] != null)
            {
                viewModel.Message = TempData["Message"].ToString();
            }
            return View(viewModel);

        }

        [HttpGet]
        public IActionResult Save(int id)
        {
            if(id == 0)
                return PartialView();

            BranchMapper branchMapper = new BranchMapper();

            var branch = db.BranchesRepository.Get(id);

            var branchModel = branchMapper.Map(branch);
            return PartialView(branchModel);
        }

        [HttpPost]
        public IActionResult Save(BranchModel model)
        {
            BranchMapper branchMapper = new BranchMapper();

            var branch = branchMapper.Map(model);

            db.BranchesRepository.Insert(branch);

            TempData["Message"] = "Operation successfully";

            return RedirectToAction("Index");
        }

    }
}

WebAzBank/Controllers/ClientController.cs
using BankApp.Core.DataAccess.Abstract;
using BankApp.WebAzBank.Mappers;
using Microsoft.AspNetCore.Mvc;
using WebAzBank.Models.Client;

namespace BankApp.WebAzBank.Controllers
{
    public class ClientController : Controller
    {
        private readonly IUnitOfWork db;

        public ClientController(IUnitOfWork db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            var clients = db.ClientRepository.Get();

            ClientMapper clientMapper = new ClientMapper();
            List<ClientModel> clientModels = new List<ClientModel>();

            for (int i = 0; i < clients.Count; i++)
            {
                var client = clients[i];
                var clientModel = clientMapper.Map(client);

                clientModel.No = i + 1;
                clientModels.Add(clientModel);
            }

            ClientViewModel viewModel = new ClientViewModel()
            {
                Clients = clientModels
            };

            return View(viewModel);

        }
    }
}

WebAzBank/Views/Branch/Index.cshtml
@using BankApp.WebAzBank.Model

@model BranchViewModel

@{ 
    ViewData["Title"] = "Branches";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

@section HeadArea
{
    <title>Branches</title>
}

<div class="dataContainer mb-3 mt-3">
    <h1 style="text-align: center;">@ViewData["Title"]</h1>
    
    @if(Model.Message != null)
    {
        <div class="divAnim">@Model.Message</div>
    }

    <table id="BranchTable" class="table table-striped table-bordered tbl" style="width:100%">
        <thead>
            <tr>
                <th>No</th>
                <th>BranchName</th>
                <th>Adress</th>
                <th>BeginWorkTime</th>
                <th>EndWorkTime</th>
                <th>Phone</th>
                <th>CountWorkers</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach(var branch in Model.Branches)
            {
                  <tr>
                  <td>@branch.No</td>
                  <td>@branch.BranchName</td>
                  <td>@branch.Adress</td>
                  <td>@branch.BeginWorkTime</td>
                  <td>@branch.EndWorkTime</td>
                  <td>@branch.Phone</td>
                  <td>@branch.CountWorkers</td>
                  <td><button class="btn btn-primary bgupdate" onclick="ShowSaveModal(this)" data-id="@branch.Id" data-target="#myModalAdd" id="btnUpdate"><i class='fas fa-download'></i> Update</button></td>
                  <td><button class="btn btn-danger bgdelete" onclick="ShowDeleteModal(this)" data-toggle="modal" data-id="@branch.Id" data-target="#DelModal" id="btnDel"><i class='fas fa-trash-alt'></i> Delete</button></td>
              </tr>
            }
        </tbody>

        <tfoot>
            <tr>
                <th>No</th>
                <th>BranchName</th>
                <th>Adress</th>
                <th>BeginWorkTime</th>
                <th>EndWorkTime</th>
                <th>Phone</th>
                <th>CountWorkers</th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
    </table>
    
    <button class="btn btn-primary bgupdate" onclick="ShowSaveModal(this)" data-toggle="modal" data-id="0" id="myBtnAdd"><i class='fas fa-download'></i> Add</button>

    <div class="modal fade" id="createModal">
        
    </div>
@section ScriptArea
{
    <script>

    function ShowDeleteModal(elem) {
        var dataId = $(elem).data("id");
        $(".deletedId").val(dataId);
    }

    function ShowSaveModal(elem) {
        var dataId = $(elem).data("id");

        $.ajax({
            url: "/Branch/Save?id=" + dataId,
            success: function (data) {
                $('#createModal').html(data);
                $("#createModal").modal("show");
            },
            error : function(error) {
                console.log(error);
            }
        });
    }
    
    $(document).ready(function () {

        $('#BranchTable tfoot th').each(function () {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search" style="width:100%;" />');
        });

        var table = $('#BranchTable').DataTable();

        table.columns().every(function () {
            var that = this;

            $('input', this.footer()).on('keyup change clear', function () {
                if (that.search() !== this.value) {
                    that.search(this.value).draw();
                }
            });
        });
    });
</script>
}

WebAzBank/Views/Branch/Save.cshtml
@using BankApp.WebAzBank.Model

@model BranchModel

<div class="modal-dialog modal-dialog-scrollable modal-lg">
    <!-- Modal content -->
    <div class="modal-content" id="editDebtModelBody">
        <div style="overflow:auto;" class="modal-body">
            <form asp-controller="Branch" asp-action="Save" class="form-group">
                <input hidden asp-for="Id"/>

               <div class="form-group">
                    <label for="name" class="mr-sm-2">Name:</label>
                    <input asp-for="BranchName" class="form-control mb-2 mr-sm-2" />
                    <span asp-validation-for="BranchName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label for="name" class="mr-sm-2">Adress:</label>
                    <input asp-for="Adress" class="form-control mb-2 mr-sm-2" />
                    <span asp-validation-for="Adress" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <label for="name" class="mr-sm-2">Phone:</label>
                    <input asp-for="Phone" class="form-control mb-2 mr-sm-2" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <label for="name" class="mr-sm-2">BeginWorkTime:</label>
                    <input asp-for="BeginWorkTime" class="form-control mb-2 mr-sm-2" />
                    <span asp-validation-for="BeginWorkTime" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label for="name" class="mr-sm-2">EndWorkTime:</label>
                    <input asp-for="EndWorkTime" class="form-control mb-2 mr-sm-2" />
                    <span asp-validation-for="EndWorkTime" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <label for="name" class="mr-sm-2">CountWorkers:</label>
                    <input asp-for="CountWorkers" class="form-control mb-2 mr-sm-2" />
                    <span asp-validation-for="CountWorkers" class="text-danger"></span>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary bgupdate">Save</button>
                </div> 
            </form>
        </div>
    </div>
</div>

<partial name="_ValidationScriptsPartial"/>

WebAzBank/Views/Client/Index.cshtml
@using WebAzBank.Models.Client
@model ClientViewModel

@{
    ViewData["Title"] = "Clients";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section HeadArea
{
<title>Banks</title>
}

<div class="dataContainer mb-3 mt-3">
    <h1 style="text-align: center;">@ViewData["Title"]</h1>

    <table id="ClientTable" class="table table-striped table-bordered tbl" style="width:100%">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Father Name</th>
                <th>FIN</th>
                <th>Seriya</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Adress</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var client in Model.Clients)
            {
                <tr>
                    <td>@client.No</td>
                    <td>@client.Name</td>
                    <td>@client.Surname</td>
                    <td>@client.FatherName</td>
                    <td>@client.FIN</td>
                    <td>@client.Seriya</td>
                    <td>@client.Phone</td>
                    <td>@client.Email</td>
                    <td>@client.Adress</td>
                    <td><button class="btn btn-primary bgupdate" onclick="ShowSaveModal(this)" data-id="@client.Id" data-target="#myModalAdd" id="btnUpdate"><i class='fas fa-download'></i> Update</button></td>
                    <td><button class="btn btn-danger bgdelete" onclick="ShowDeleteModal(this)" data-toggle="modal" data-id="@client.Id" data-target="#DelModal" id="btnDel"><i class='fas fa-trash-alt'></i> Delete</button></td>
                </tr>
            }
        </tbody>

        <tfoot>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Father Name</th>
                <th>FIN</th>
                <th>Seriya</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Adress</th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
    </table>

    <button class="btn btn-primary bgupdate" onclick="ShowSaveModal(this)" data-toggle="modal" data-id="0" id="myBtnAdd"><i class='fas fa-download'></i> Add</button>

    @section ScriptArea
    {
    <script>

        function ShowDeleteModal(elem) {
            var dataId = $(elem).data("id");
            $(".deletedId").val(dataId);
        }

        function ShowSaveModal(elem) {
            var dataId = $(elem).data("id");

            $.ajax({
                url: "/Bank/Save?id=" + dataId,
                success: function (data) {
                    $('#createModal').html(data);
                    $("#createModal").modal("show");
                },
                error : function(error) {
                    console.log(error);
                }
            });
        }

        $(document).ready(function () {

            $('#ClientTable tfoot th').each(function () {
                var title = $(this).text();
                $(this).html('<input type="text" placeholder="Search" style="width:100%;" />');
            });

            var table = $('#ClientTable').DataTable();

            table.columns().every(function () {
                var that = this;

                $('input', this.footer()).on('keyup change clear', function () {
                    if (that.search() !== this.value) {
                        that.search(this.value).draw();
                    }
                });
            });
        });
    </script>
    }

WebAzBank/Views/Shared/_Layout.cshtml
@using WasherWeb.Areas.Owners.Models;
 
@{
    Layout = null;
    List<CommonMenuModel> menuOrders = new List<CommonMenuModel>();
} 

<!DOCTYPE html>

<html>
<head>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <link rel="shortcut icon" href="~/images/logos/Ecosteamobile-01.png">
    <link href="~/images/logos/Ecosteamobile-01.png" rel="apple-touch-icon">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/DataTables/datatables.min.css" />
    <link rel="stylesheet" href="~/css/pagination.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/layout.css" />
    <link rel="stylesheet" href="~/css/text-editor.css" />
    <link rel="stylesheet" href="~/css/admin.crud.css">
    <link rel="stylesheet" href="~/css/warninganimation.css">
    <link rel="stylesheet" href="~/css/progress.css">

    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript" src="~/DataTables/datatables.min.js"></script>

    @RenderSection("HeadArea", false)
</head>

<body style="overflow-x:hidden;overflow-y:auto">
    <partial name="header"/>
    <div style="height:100vh;">
        <div class="container-flud h-100" style="padding-top:56px;">
            <div class="row h-100">
                <div id="sidebar" class="col-sm-12 col-md-3 col-lg-2 col-xl-2">
                    <div class="list-group list-group-flush">
                        @{ int count = 0;
                                menuOrders.Add(new MenuModel(count++, "Clients", "Index", "Client"));
                                menuOrders.Add(new MenuModel(count++, "Bank Branches", "Index", "BankBranch"));
                        }

                        @foreach (var menu in menuOrders)
                        {
                            if (menu is ParentMenuModel parentMenuModel)
                            {
                                       <span class="list-group-item list-group-item-action">@parentMenuModel.Name</span>
                                        <ul id="myUL">
                                            <li>
                                                <ul class="nested">
                                                    @foreach (var childMenu in parentMenuModel.ChildModels)
                                                    {
                                                        <li>
                                                            <a asp-action="@childMenu.Action" asp-controller="@childMenu.Controller" class="sequence list-group-item list-group-item-action">@childMenu.Name</a>
                                                        </li>
                                                    }
                                                </ul>
                                            </li>
                                        </ul> 
                            }
                            else if (menu is MenuModel menuModel)
                            {
                                 <a asp-action="@menuModel.Action" asp-controller="@menuModel.Controller" class="sequence list-group-item list-group-item-action">@menuModel.Name</a>
                            }
                        }
                    </div>
                </div>
                <div id="content" class="col-sm-12 col-md-9 col-lg-10 col-xl-10 p-0">
                    <div id="content-header" class="w-100 text-white p-2 bg-info shadow">Test</div>

                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
           @{
                   var actionName = ViewContext.RouteData.Values["action"].ToString();

                   int order = 0;
                   string menuName = string.Empty;

                   foreach (var menu in menuOrders)
                   {
                       bool haveInMenu = menu.HaveInMenu(actionName, out order, out menuName);

                       if (haveInMenu)
                           break;
                   }
               }

            $('.sequence').eq(@order).addClass('active text-white');
            $('#content-header').text('@menuName');

            $('#btn-toggler').click(function () {
                $('#sidebar').eq(0).slideToggle();
               });
        });

        var toggler = document.getElementsByClassName("caret");
        var i;

        for (i = 0; i < toggler.length; i++) {
            toggler[i].addEventListener("click", function() {
            this.parentElement.querySelector(".nested").classList.toggle("active");
             this.classList.toggle("caret-down");
            });
        }
    </script>

    @RenderSection("ScriptArea", false)
</body>
</html>

WebAzBank/Views/Shared/header.cshtml
    <nav class="navbar navbar-expand-md navbar-dark shadow fixed-top bg-dark flex-md-nowrap justify-content-between">
        <a class="navbar-brand" asp-action="Index" asp-controller="Banks">USER@*@User.Identity?.Name*@</a>
        <div>
            <button class="navbar-toggler" id="btn-toggler" type="button" data-toggle="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <a asp-controller="Account" asp-action="Logout" class="btn btn-outline-light">Sign out</a>
        </div>
    </nav>